apiVersion: v1
kind: Service
metadata:
  name: docker-demo
spec:
  type: NodePort #so we can access it outside the cluster
  selector:
    app: docker-demo
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
      nodePort: 30100
